title: <p align="center"> Rahul Prashar </p>
logo: /assets/img/1600440265363.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rahul-prashar/">LinkedIn</a> |
  <a href="https://github.com/rahulprashar25">GitHub</a>
  
  <br>   
  7+ years of industry experience across multiple functions including Strategy & Operations,Business Analytics, Sales Force Effectiveness, Business Intelligence and Data Management.
  Currently working in Novartis and leading Business Intelligence and Commercial Analytics
  <br>
  </p>



theme: jekyll-theme-minimal
